spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/mercadolivro?createDatabaseIfNotExist=true&useTimezone=true&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  jackson:
    default-property-inclusion: non_null
  mvc:
    pathmatch:
      matchin-strategy: ant_path_matcher

jwt:
  secret: 56a69d5d-2ebb-4bfc-bf06-eda1126cea82
  expiration: 999999
